function [filemat] = GetFileNames()
    fileNames = ['e' 's' 'num4' 'star' 'gesture5'...
        'num8' 'gesture7' 'su 'mi' 'wang'...
        'ru' 'miu' 'm' 'gesture14' 'gesture15'...
        'gesture16' 'gesture17'];
    
    fileMat = [(1:17)' fileNames'];
end
    